// src/utils/staticCourses.js
// Shared course list used as fallback when database is not connected

export const STATIC_COURSES = [
  { id: 's1',  code: 'MA101',  title: 'Real Analysis 1',                               level: 'Level 1', description: 'Foundations of real number analysis, sequences and series.' },
  { id: 's2',  code: 'CS101',  title: 'Computing in Society',                          level: 'Level 1', description: 'Impact of computing on society, ethics and digital citizenship.' },
  { id: 's3',  code: 'CS102',  title: 'PC Hardware',                                   level: 'Level 1', description: 'Computer hardware components, assembly and troubleshooting.' },
  { id: 's4',  code: 'CS103',  title: 'Algorithm and Data Structure 1',                level: 'Level 1', description: 'Introduction to algorithms, complexity and basic data structures.' },
  { id: 's5',  code: 'CS104',  title: 'Research Methodology',                          level: 'Level 1', description: 'Scientific research methods, writing and academic integrity.' },
  { id: 's6',  code: 'CS105',  title: 'Object Oriented Programming',                   level: 'Level 1', description: 'OOP concepts: classes, inheritance, polymorphism and encapsulation.' },
  { id: 's7',  code: 'MA102',  title: 'Linear Algebra',                                level: 'Level 1', description: 'Vectors, matrices, linear transformations and eigenvalues.' },
  { id: 's8',  code: 'MA201',  title: 'Real Analysis 2',                               level: 'Level 1', description: 'Advanced real analysis, continuity, differentiation and integration.' },
  { id: 's9',  code: 'GE201',  title: 'Knowledge Leadership and African Development',  level: 'Level 1', description: 'Leadership, knowledge management and African development context.' },
  { id: 's10', code: 'MA202',  title: 'Discrete Mathematics',                          level: 'Level 1', description: 'Logic, sets, graph theory and combinatorics.' },
  { id: 's11', code: 'CS201',  title: 'Algorithm and Data Structure 2',                level: 'Level 1', description: 'Advanced algorithms: sorting, trees, graphs and dynamic programming.' },
  { id: 's12', code: 'MA203',  title: 'Probability and Statistics',                    level: 'Level 2', description: 'Probability theory, distributions, hypothesis testing and inference.' },
  { id: 's13', code: 'CS202',  title: 'Introduction to Software Engineering',          level: 'Level 2', description: 'SDLC, software processes, requirements engineering and project management.' },
  { id: 's14', code: 'CS203',  title: 'Java Programming 1',                            level: 'Level 2', description: 'Java fundamentals, OOP in Java, exception handling and collections.' },
  { id: 's15', code: 'CS204',  title: 'Python Programming',                            level: 'Level 2', description: 'Python basics, data structures, file handling and libraries.' },
  { id: 's16', code: 'CS205',  title: 'Computer Organization and Architecture',        level: 'Level 2', description: 'CPU design, memory hierarchy, instruction sets and pipelines.' },
  { id: 's17', code: 'GE202',  title: 'Technical Writing',                             level: 'Level 2', description: 'Technical documentation, reports, proposals and presentations.' },
  { id: 's18', code: 'MA204',  title: 'Computational Mathematics',                     level: 'Level 2', description: 'Numerical methods, approximation and computational problem solving.' },
  { id: 's19', code: 'CS206',  title: 'Java Programming 2',                            level: 'Level 2', description: 'Advanced Java: multithreading, GUI, networking and design patterns.' },
  { id: 's20', code: 'GE203',  title: 'Civics and Ethics',                             level: 'Level 2', description: 'Civic responsibility, professional ethics and legal frameworks in ICT.' },
  { id: 's21', code: 'CS301',  title: 'Operating System',                              level: 'Level 2', description: 'OS concepts: processes, memory management, file systems and scheduling.' },
  { id: 's22', code: 'CS302',  title: 'Database Management System',                    level: 'Level 2', description: 'Relational databases, SQL, normalization and transaction management.' },
  { id: 's23', code: 'CS303',  title: 'Object Oriented Analysis, Design and Implementation', level: 'Level 2', description: 'UML, design patterns, system modeling and implementation strategies.' },
  { id: 's24', code: 'CS304',  title: 'Introduction to Game Development',              level: 'Level 2', description: 'Game design principles, engines, graphics and interactive media.' },
  { id: 's25', code: 'CS305',  title: 'Introduction to IoT',                           level: 'Level 2', description: 'Internet of Things, sensors, embedded systems and smart devices.' },
  { id: 's26', code: 'CS306',  title: 'Computer Network and Security',                 level: 'Level 2', description: 'Network protocols, TCP/IP, firewalls and security fundamentals.' },
  { id: 's27', code: 'CS307',  title: 'Cybersecurity',                                 level: 'Level 3', description: 'Threats, cryptography, penetration testing and security policies.' },
  { id: 's28', code: 'CS308',  title: 'Wide Area Network',                             level: 'Level 3', description: 'WAN technologies, routing protocols and enterprise networking.' },
  { id: 's29', code: 'CS309',  title: 'Software Modeling and Design',                  level: 'Level 3', description: 'Software architecture, design principles and modeling techniques.' },
  { id: 's30', code: 'CS310',  title: 'Relational Database',                           level: 'Level 3', description: 'Advanced relational database design, optimization and administration.' },
  { id: 's31', code: 'CS311',  title: 'Wireless and Mobile Networks',                  level: 'Level 3', description: 'Wireless protocols, mobile computing and network infrastructure.' },
  { id: 's32', code: 'CS312',  title: 'CCNA 1',                                        level: 'Level 3', description: 'Cisco networking fundamentals, routing, switching and network configuration.' },
  { id: 's33', code: 'CS313',  title: 'Agile Professional',                            level: 'Level 3', description: 'Agile methodologies, Scrum, Kanban and modern project delivery.' },
];